/*
** EPITECH PROJECT, 2019
** RogueLike
** File description:
** main
*/

#include <limits>
#include <iostream>
#include <fstream>
#include <cstdlib>
#include <getopt.h>
#include "Raytracer/Shape/Sphere.hpp"
#include "Raytracer/Shape/Box.hpp"
#include "Raytracer/HitList.hpp"
#include "Raytracer/Camera.hpp"
#include "Raytracer/Material.hpp"
#include "Raytracer/Random.hpp"
#include "Image/Image.hpp"
#include "VoxelOctree/VoxelOctree.hpp"

static const char *soptions = "o:w:h:s:";

static const struct option loptions[] = {
    {"object", required_argument, 0, 'o'},
    {"width", required_argument, 0, 'w'},
    {"height", required_argument, 0, 'h'},
    {"samples", required_argument, 0, 's'},
    {0, 0, 0, 0}
};

void print_usage(char const *name)
{
    printf(
        "\nUsage %s --object name --width nx --height ny --samples ns\n"
        "\t--object\t|\t-o\tName of the image generated by the program\n"
        "\t--width\t|\t-w\tWidth of the image generated by the program\n"
        "\t--height\t|\t-h\tHeight of the image generated by the program\n"
        "\t--samples\t|\t-s\tNumber of samples use by the program to generate the image\n",
        name
    );
}

bool process_params(int ac, char **av, std::string& name, int& width, int& height, int& samples)
{
    int long_index = 0;
    int opt = 0;

    while ((opt = getopt_long(ac, av, soptions, loptions, &long_index)) != -1) {
        switch (opt) {
            case 'o':
                name = optarg;
                break;
            case 'w':
                width = atoi(optarg);
                break;
            case 'h':
                height = atoi(optarg);
                break;
            case 's':
                samples = atoi(optarg);
                break;
            default:
                print_usage(av[0]);
                return false;
        }
    }
    return true;
}

glm::vec3 color(const ray& r, VoxelOctree *vo, int depth)
{
    Record rec;
    if (VoxelOctree_Intersect(vo, r, 0.001, std::numeric_limits<float>::max(), rec)) {
        return rec.color;
    } else {
        glm::vec3 unit_dir = glm::normalize(r.direction());
        float t = 0.5 * (unit_dir.y + 1.0f);
        return (1.0f - t) * glm::vec3(1.0, 1.0, 1.0) + t * glm::vec3(0.5, 0.7, 1.0);
    }
}

int main(int ac, char **av)
{
    int nx = 1920;
    int ny = 1080;
    int ns = 1;
    std::string name("../raytraced.png");
    if (!process_params(ac, av, name, nx, ny, ns))
        return 1;
    Image img(nx, ny);
    camera cam(glm::vec3(10, 10, 10), glm::vec3(0, 0, 0), glm::vec3(0, 1, 0), 90, float(nx) / float(ny));

    VoxelOctree *vo = VoxelOctree_create(glm::vec3(0, 0, 0), 1, 4);

    VoxelInfo vi;
    vi.x = 0;
    vi.y = 0;
    vi.z = 0;
    vi.color = glm::vec3(1, 0, 0);

    VoxelOctree_insert(vo, vi);

    for (int j = 0; j < ny; ++j) {
        for (int i = 0; i < nx; i++) {
            glm::vec3 col(0.f, 0.f, 0.f);
            for (int s = 0; s < ns; s++) {
                float u = float(i + randf()) / float(nx);
                float v = float(j + randf()) / float(ny);
                ray r = cam.get_ray(u, v);
                col += color(r, vo, 0);
            }
            col /= float(ns);
            col = glm::sqrt(col);
            img.setPixel(i, j, col);
        }
    }
    img.SaveAs(name);
    VoxelOctree_destroy(vo);
    return (0);
}